name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.15.3"
      - name: Cache yarn
        uses: actions/cache@v2
        with:
          path: node_modules
          key: yarn-cache-${{ hashFiles('yarn.lock') }}
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn test
